### ISSUE TITLE
Question about Uboot Console

### ISSUE THREAD

**Issue by RobertHerreraEECS** [darkarnium/sonor#4]
You list the pin out in the "Serial Console" and then in the next sectio you dump the uboot cli. I've seen other reports about S1 Gen 2 that state that the uboot console is locked down but you list the uboot console display in the next section (U-boot). 

Is this a natively compiled equivalent build of the uboot version that's running on the Gen 2 or is the actual console output because mine is not interactive, which I suspect is because of a lack of a boot delay.

**Comment by darkarnium** [comment]
Hey there,

The output in this repository is the output from the device over the serial console from the S1 running an older build of software. However, Sonos since fixed the `i2c` bugs discussed in this repository, entirely locked down access to U-Boot, and even fixed subsequent bugs we found that allowed regaining access to U-Boot by glitching past password prompts.

Sonos are quite good at patching all of the bypasses and bugs posted publicly, so any subsequent bypasses and techniques haven't been published :)

**Comment by RobertHerreraEECS** [comment]
Gotcha, thank you for the quick response! :)
